# Generated by Django 5.0.6 on 2024-06-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_html', models.TextField(blank=True, null=True)),
                ('descriptor_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elama.descriptor')),
                ('principio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.principio')),
            ],
            options={
                'verbose_name_plural': 'descriptores',
            },
        ),
    ]
