# Generated by Django 5.1.7 on 2025-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elama", "0003_autoevaluacion_usuario_grupo_autoevaluacion_grupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
