# Generated by Django 5.1.7 on 2025-04-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elama", "0004_grupo_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoAutoevaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autoevaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elama.autoevaluacion",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elama.grupo"
                    ),
                ),
            ],
        ),
    ]
