# Generated by Django 5.1.7 on 2025-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elama", "0005_grupoautoevaluacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="volcado",
            name="logro",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="volcado",
            name="mejora",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="GrupoAutoevaluacion",
        ),
    ]
