# Generated by Django 5.1.8 on 2025-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elama', '0007_alter_descriptor_contenido_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='principio',
            name='step',
            field=models.IntegerField(null=True),
        ),
    ]
